export const chapters =[{
    id:0,
    name:"chapter0_title",
    description:"chapter0_desc"
}, {
    id:1,
    name:"chapter1_title",
    description:"chapter1_desc"
}, {
    id:2,
    name:"chapter2_title",
    description: "chapter2_desc"
}, {
    id:3,
    name: "chapter3_title",
    description:"chapter3_desc"
}, {
    id:4,
    name:"chapter4_title",
    description:"chapter4_desc"
}, {
    id:5,
    name:"chapter5_title",
    description:"chapter5_desc"
}, {
    id:6,
    name:"chapter6_title",
    description:"chapter6_desc"
}]

export const chapter1 =[{
    id:0,
    exam: false,
    name:"chapter1-lesson1"
},{
    id:1,
    exam: false,
    name:"chapter1-lesson2"
},{
    id:2,
    exam: false,
    name: "chapter1-lesson3"
},{
    id:3,
    exam: false,
    name: "chapter1-lesson4"
},{
    id:4,
    exam: false,
    name:"chapter1-lesson5"
},{
    id:5,
    exam: false,
    name:"chapter1-lesson6"
}, {
    id:101,
    exam:true,
    name:"chapter1_exam"
}]

export const chapter2 = [{
    id:100,
    exam:true,
    name:"chapter2_lesson0"
},{
    id:1,
    exam:false,
    name:"chapter2-lesson1",
},{
    id:2,
    exam:false,
    name:"chapter2-lesson2"
},{
    id:3,
    exam:false,
    name:"chapter2-lesson3"
},{
    id:4,
    exam:false,
    name:"chapter2-lesson4"
},{
    id:101,
    exam:true,
    name:"chapter2_exam1"
},{
    id:102,
    exam:true,
    name:"chapter2_exam2"
}]

export const chapter3 = [{
    id:0,
    exam:false,
    name:"chapter3-lesson1"
},{
    id:1,
    exam:false,
    name:"chapter3-lesson2"
},{
   id:2,
   exam:false,
   name:"chapter3-lesson3" 
},{
    id:3,
    exam:false,
    name:"chapter3-lesson4"
},{
    id:4,
    exam:false,
    name:"chapter3-lesson5"
},{
    id:5,
    exam:false,
    name:"chapter3-lesson6"
},{
    id:101,
    exam:true,
    name:"chapter3_exam1"
},{
    id:102,
    exam:true,
    name:"chapter3_exam2"
},{
    id:6,
    exam:false,
    name:"chapter3-lesson7"
},{
    id:7,
    exam:false,
    name:"chapter3-lesson8"
},{
    id:8,
    exam:false,
    name:"chapter3-lesson9"
},{
    id:9,
    exam:false,
    name:"chapter3-lesson10"
},{
    id:103,
    exam:true,
    name:"chapter3_exam3"
},{
    id:104,
    exam:true,
    name:"chapter3_exam4"
}]

export const chapter4 = [{
    id:0,
    exam:false,
    name:"chapter4-lesson1"
},{
    id:1,
    exam:false,
    name:"chapter4-lesson2"
},{
    id:2,
    exam:false,
    name:"chapter4-lesson3"
},{
    id:3,
    exam:false,
    name:"chapter4-lesson4"
},{
    id:4,
    exam:false,
    name:"chapter4-lesson5"
},{
    id:5,
    exam:false,
    name:"chapter4-lesson6"
},{
    id:101,
    exam:true,
    name:"chapter4_exam1"
},{
    id:102,
    exam:true,
    name:"chapter4_exam2"
},{
    id:6,
    exam:false,
    name:"chapter4-lesson7"
},{
    id:7,
    exam:false,
    name:"chapter4-lesson8"
},{
    id:8,
    exam:false,
    name:"chapter4-lesson9"
},{
    id:9,
    exam:false,
    name:"chapter4-lesson10"
},{
    id:103,
    exam:true,
    name:"chapter4_exam3"
},{
    id:104,
    exam:true,
    name:"chapter4_exam4"
}]

export const chapter5 = [{
    id:100,
    exam:true,
    name:"chapter5_lesson0"
},{
    id:1,
    exam:false,
    name:"chapter5-lesson1"
},{
    id:2,
    exam:false,
    name:"chapter5-lesson2"
},{
    id:3,
    exam:false,
    name:"chapter5-lesson3"
},{
    id:4,
    exam:false,
    name:"chapter5-lesson4"
},{
    id:5,
    exam:false,
    name:"chapter5-lesson5"
},{
    id:6,
    exam:false,
    name:"chapter5-lesson6"
},{
    id:101,
    exam:true,
    name:"chapter5_exam1"
},{
    id:7,
    exam:false,
    name:"chapter5-lesson7"
},{
    id:8,
    exam:false,
    name:"chapter5-lesson8"
},{
    id:9,
    exam:false,
    name:"chapter5-lesson9"
},{
    id:10,
    exam:false,
    name:"chapter5-lesson10"
},{
    id:11,
    exam:false,
    name:"chapter5-lesson11"
},{
    id:12,
    exam:false,
    name:"chapter5-lesson12"
},{
    id:102,
    exam:true,
    name:"chapter5_exam2"
},{
    id:103,
    exam:true,
    name:"chapter5_exam3"
},{
    id:13,
    exam:false,
    name:"chapter5-lesson13"
},{
    id:14,
    exam:false,
    name:"chapter5-lesson14"
},{
    id:15,
    exam:false,
    name:"chapter5-lesson15"
},{
    id:16,
    exam:false,
    name:"chapter5-lesson16"
},{
    id:17,
    exam:false,
    name:"chapter5-lesson17"
},{
    id:18,
    exam:false,
    name:"chapter5-lesson18"
},{
    id:104,
    exam:true,
    name:"chapter5_exam4"
},{
    id:105,
    exam:true,
    name:"chapter5_exam5"
}]

export const chapter6 = [{
    id:100,
    exam:true,
    name:"chapter6_lesson0"
},{
    id:1,
    exam:false,
    name:"chapter6-lesson1"
},{
    id:2,
    exam:false,
    name:"chapter6-lesson2"
},{
    id:3,
    exam:false,
    name:"chapter6-lesson3"
},{
    id:4,
    exam:false,
    name:"chapter6-lesson4"
},{
    id:5,
    exam:false,
    name:"chapter6-lesson5"
},{
    id:6,
    exam:false,
    name:"chapter6-lesson6"
},{
    id:101,
    exam:true,
    name:"chapter6_exam1"
},{
    id:7,
    exam:false,
    name:"chapter6-lesson7"
},{
    id:8,
    exam:false,
    name:"chapter6-lesson8"
},{
    id:9,
    exam:false,
    name:"chapter6-lesson9"
},{
    id:10,
    exam:false,
    name:"chapter6-lesson10"
},{
    id:11,
    exam:false,
    name:"chapter6-lesson11"
},{
    id:12,
    exam:false,
    name:"chapter6-lesson12"
},{
    id:102,
    exam:true,
    name:"chapter6_exam2"
},{
    id:103,
    exam:true,
    name:"chapter6_exam3"
},{
    id:13,
    exam:false,
    name:"chapter6-lesson13"
},{
    id:14,
    exam:false,
    name:"chapter6-lesson14"
},{
    id:15,
    exam:false,
    name:"chapter6-lesson15"
},{
    id:16,
    exam:false,
    name:"chapter6-lesson16"
},{
    id:17,
    exam:false,
    name:"chapter6-lesson17"
},{
    id:18,
    exam:false,
    name:"chapter6-lesson18"
},{
    id:104,
    exam:true,
    name:"chapter6_exam4"
},{
    id:105,
    exam:true,
    name:"chapter6_exam5"
}]